// redux-vs-vuex/vuex-todo/src/components/List/index.vue
<template>
  <div class="col-6">
    <h3>Todos</h3>
    <ul v-show="todos.length">
      <li
        v-for="todo in todos"
        :key="todo.id"
        class="list-group-item d-flex align-items-center"
      >
        <Regular :todo="todo" v-if="!todo.edit" />
        <Edit :todo="todo" v-else />
      </li>
    </ul>
  </div>
</template>

<script>
// Утилита для привязки геттеров к компоненту
import { mapGetters } from 'vuex'
// Компонент для обычной задачи
import Regular from './Regular'
// Компонент для редактируемой задачи
import Edit from './Edit'

export default {
  name: 'List',
  components: { Regular, Edit },
  computed: {
    // Привязываем геттер к компоненту
    ...mapGetters({ todos: 'filteredTodos' })
  }
}
</script>

// React/redux-vs-vuex/react-todo/src/components/List/index.jsx
import { useAppContext } from '../../context'

import Regular from './Regular'
import Edit from './Edit'

export default function List() {
  const { selectors } = useAppContext()
  const filteredTodos = selectors.selectFilteredTodos()

  return (
    <div className=' col-6'>
      <h3>Todos</h3>
      <ul className='list-group'>
        {filteredTodos.map((todo) =>
          todo.edit ? (
            <Edit key={todo.id} todo={todo} />
          ) : (
            <Regular key={todo.id} todo={todo} />
          )
        )}
      </ul>
    </div>
  )
}
