// redux-vs-vuex/vuex-todo/src/components/List/Regular.vue
<template>
  <input
    type="checkbox"
    :checked="todo.done"
    @change="completeTodo"
    class="form-check-input"
  />
  <p class="flex-grow-1 m-0" :class="todoClass">
    {{ todo.text }}
  </p>
  <button @click="editTodo" class="btn btn-outline-info" :disabled="todo.done">
    <i class="bi bi-pencil"></i>
  </button>
  <button @click="removeTodo(todo)" class="btn btn-outline-danger">
    <i class="bi bi-trash"></i>
  </button>
</template>

<script>
// Утилита для привязки операций к методам компонента
import { mapActions } from 'vuex'

export default {
  name: 'Regular',
  props: ['todo'],
  computed: {
    // Вычисляем дополнительный CSS-класс для задачи
    todoClass() {
      return this.todo.done ? 'text-muted text-decoration-line-through' : ''
    }
  },
  methods: {
    // Привязываем операции к методам компонента
    ...mapActions(['updateTodo', 'removeTodo']),
    // Метод для изменения индикатора завершенности задачи
    completeTodo() {
      this.updateTodo({ id: this.todo.id, changes: { done: !this.todo.done } })
    },
    // Метод для изменения индикатора редактирования задачи
    editTodo() {
      this.updateTodo({ id: this.todo.id, changes: { edit: !this.todo.edit } })
    }
  }
}
</script>

// React/redux-vs-vuex/react-todo/src/components/List/Regular.jsx
import { useAppContext } from '../../context'

export default function Regular({ todo }) {
  const { dispatch, actions } = useAppContext()
  const { id, text, done, edit } = todo

  return (
    <li className='list-group-item d-flex align-items-center'>
      <input
        type='checkbox'
        checked={done}
        onChange={() =>
          dispatch(actions.updateTodo({ id, changes: { done: !done } }))
        }
        className='form-check-input'
      />
      <p
        className={`flex-grow-1 m-0 ${
          done ? 'text-muted text-decoration-line-through' : ''
        }`}
      >
        {text}
      </p>
      <button
        onClick={() =>
          dispatch(actions.updateTodo({ id, changes: { edit: !edit } }))
        }
        className='btn btn-outline-info'
        disabled={done}
      >
        <i className='bi bi-pencil'></i>
      </button>
      <button
        onClick={() => dispatch(actions.removeTodo(id))}
        className='btn btn-outline-danger'
      >
        <i className='bi bi-trash'></i>
      </button>
    </li>
  )
}
