// React/redux-vs-vuex/redux-todo/src/components/Filters.jsx
// Хуки для получения диспетчера и селекторов
import { useDispatch, useSelector } from 'react-redux'
// Операция для установки значения фильтра
import { setFilter } from '../store'

// Фильтры
export default function Filters() {
  // Получаем диспетчера
  const dispatch = useDispatch()
  // Получаем текущее значение фильтра
  const { status } = useSelector((state) => state.filter)

  return (
    <div className='col-3'>
      <h3>Filters</h3>
      {['all', 'active', 'completed'].map((filter) => (
        <div key={filter} className='form-check' style={{ textAlign: 'left' }}>
          <input
            id={filter}
            type='radio'
            checked={filter === status}
            onChange={() => dispatch(setFilter(filter))}
            className='form-check-input'
          />
          <label htmlFor={filter} className='form-check-label'>
            {filter.toUpperCase()}
          </label>
        </div>
      ))}
    </div>
  )
}

// React/redux-vs-vuex/vuex-todo/src/components/Filters.vue
<template>
  <div class="col-3">
    <h3>Filters</h3>
    <div
      v-for="filter in ['all', 'active', 'completed']"
      :key="filter"
      class="form-check text-left"
    >
      <input
        :id="filter"
        type="radio"
        :checked="filter === currentFilter"
        @click="setFilter(filter)"
        class="form-check-input"
      />
      <label :for="filter" class="form-check-label">
        {{ filter.toUpperCase() }}
      </label>
    </div>
  </div>
</template>

<script>
// Утилита для привязки операций к методам компонента
import { mapActions } from 'vuex'

export default {
  name: 'Filters',
  computed: {
    // Получаем текущее значение фильтра
    currentFilter() {
      return this.$store.state.filter
    }
  },
  methods: {
    // Привязываем операцию к методу компонента
    ...mapActions(['setFilter'])
  }
}
</script>

<style scoped>
.text-left {
  text-align: left !important;
}
</style>
