// redux-vs-vuex/react-todo/src/components/Stats.jsx
import { useAppContext } from '../context'

export default function Stats() {
  const { selectors } = useAppContext()
  const stats = selectors.selectTodoStats()

  return (
    <div className='row'>
      <h3>Statistics</h3>
      <table className='table text-center'>
        <thead>
          <tr>
            {Object.keys(stats).map(([first, ...rest], index) => (
              <th scope='col' key={index}>
                {`${first.toUpperCase()}${rest.join('').toLowerCase()}`}
              </th>
            ))}
          </tr>
          <tr>
            {Object.values(stats).map((value, index) => (
              <td key={index}>{value}</td>
            ))}
          </tr>
        </thead>
      </table>
    </div>
  )
}

// React/redux-vs-vuex/vuex-todo/src/components/Stats.vue
<template>
  <div class="row">
    <h3>Statistics</h3>
    <table class="table text-center">
      <thead>
        <tr>
          <th scope="col" v-for="(_, name, index) in todoStats" :key="index">
            {{ `${name[0].toUpperCase()}${name.slice(1).toLowerCase()}` }}
          </th>
        </tr>
        <tr>
          <td v-for="(val, _, index) in todoStats" :key="index">{{ val }}</td>
        </tr>
      </thead>
    </table>
  </div>
</template>

<script>
// Утилита для привязки геттеров к компоненту
import { mapGetters } from 'vuex'

export default {
  name: 'Stats',
  computed: {
    // Привязываем геттер к компоненту
    ...mapGetters(['todoStats'])
  }
}
</script>
