// redux-vs-vuex/vuex-todo/src/components/Controls.vue
<template>
  <div class="col-3 d-flex flex-column">
    <h3>Controls</h3>
    <template v-if="length">
      <button @click="completeTodos" class="btn btn-info mb-2">Complete</button>
      <button @click="clearCompleted" class="btn btn-danger mb-2">Clear</button>
    </template>
    <button @click="saveTodos" class="btn btn-success">Save</button>
  </div>
</template>

<script>
// Утилита для привязки операций к методам компонента
import { mapActions } from 'vuex'

export default {
  name: 'Controls',
  computed: {
    // Вычисляем длину массива с задачами
    length() {
      return this.$store.state.todos.length
    }
  },
  methods: {
    // Привязываем операции к методам компонента
    ...mapActions(['completeTodos', 'clearCompleted', 'saveTodos'])
  }
}
</script>

// redux-vs-vuex/react-todo/src/components/Controls.jsx
import { useAppContext } from '../context'

export default function Controls() {
  const { state, dispatch, actions } = useAppContext()
  const { todos } = state

  return (
    <div className='col-3 d-flex flex-column'>
      <h3>Controls</h3>
      {todos.length ? (
        <>
          <button
            onClick={() => dispatch(actions.completeTodos())}
            className='btn btn-info mb-2'
          >
            Complete
          </button>
          <button
            onClick={() => dispatch(actions.clearCompleted())}
            className='btn btn-danger mb-2'
          >
            Clear
          </button>
        </>
      ) : null}
      <button
        onClick={() => dispatch(actions.saveTodos(todos))}
        className='btn btn-success'
      >
        Save
      </button>
    </div>
  )
}
